################################################################################
### Load packages
################################################################################

options(warn=-1)

library(RODBC)
library(data.table)
library(dplyr)
library(sqldf)
library(lubridate)
library(timeDate)
library(forecast)
library(ggplot2)
library(plotly)
library(zoo)
library(writexl)
library(lubridate)
library(knitrProgressBar)
library(parallel)
library(readxl)
library(tictoc)
library(reshape2)
library(tidyverse)
library(corrplot)
library(vars)

library(neuralnet)
library(MASS)
library(anytime)
library(pracma)
library(TTR)
library(RcppRoll)
library(pracma)
library(rlang)
library(htmlwidgets)
library(tibble)
library(markdown)
library(rsconnect)
